### ISSUE TITLE
Issue connecting to a local dev elastic server

### ISSUE THREAD

**Issue by rs82uk** [appbaseio/dejaVu#165]
I am using the Chrome Extension version of dejavu

I get the following error message

> It looks like your app name, username, password combination doesn't match. Check your url and appname and then connect it again

Error in console is 

> WebSocket connection to 'ws://localhost:9200/myindex' failed: Error during WebSocket handshake: Unexpected response code: 200

from reading some posts online it appears i need to change my elastic config

I have changed my config in elasticsearch.yml to the following with no joy

`bootstrap.memory_lock: false
cluster.name: elasticsearch
http.port: 9200
network.host: SB-DEVSVR01
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: SB-DEVSVR01
path.data: C:\ProgramData\Elastic\Elasticsearch\data
path.logs: C:\ProgramData\Elastic\Elasticsearch\logs
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.cors.allow-credentials: true
http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length"`

**Comment by siddharthlatest** [comment]
The console error isn't the root cause. Are you using a proper scheme when you set the cluster URL? Also, dejavu expects your index to exist when you connect to it.

**Comment by rs82uk** [comment]
proper scheme? and yes the index exists

**Comment by aario** [comment]
Same here with docker-compose. No error. No nothing. Just doesn't work.
Docker compose file:
```
    elasticsearch:
      image: elasticsearch:latest
      container_name: elasticsearch
      environment:
        - cluster.name=catalog
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.ping.unicast.hosts=elasticsearch"
        - http.cors.allow-origin="/.*/"
        - http.cors.enabled=true
        - http.cors.allow-headers="X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
        - http.cors.allow-credentials="true"
      ports:
       - "9200:9200"
      volumes:
        - ${VOL_DIR}/elasticsearch:/usr/share/elasticsearch/data
    dejavu:
      image: appbaseio/dejavu:latest
      container_name: dejavu
      ports:
       - "1358:1358"
      links:
        - elasticsearch
```
I can see:
 - http://localhost:1358/live/
 - http://localhost:9200/
I can wget http://elasticsearch:9200/ from dejavu container.
So far I tried this:
```
AppName: elasticsearch
URL: http://localhost:9200/
```
And:
```
AppName: D5SOLJK
URL: http://localhost:9200/
```
And:
```
AppName: elasticsearch
URL: http://elasticsearch:9200/
```
And:
```
AppName: D5SOLJK
URL: http://elasticsearch:9200/
```
Here is the output of http://elasticsearch/

name | "D5SOLJK"
-- | --
cluster_name | "elasticsearch"
cluster_uuid | "mkjLdd0LS96E66iy91m2wg"
version |  
number | "5.6.8"
build_hash | "688ecce"
build_date | "2018-02-16T16:46:30.010Z"
build_snapshot | false
lucene_version | "6.6.1"
tagline | "You Know, for Search"

Where can I see error messages on connection (If there is any)?
Where can I get/set username and password of elasticsearch?

**Comment by aario** [comment]
Ok. Seems like errors are actually happening in the browser itself and not in backend. So the problem for me is that although I put `- http.cors.allow-origin="/.*/"` in docker-compose.yml, the elasticsearch still doesn't allow the client:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9200/elasticsearch/_mapping?. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
Would be great if there was a docker-compose.yml example.

**Comment by siddharthlatest** [comment]
@aario thanks, I am able to replicate the issue. Will get back soon on the root cause.

**Comment by siddharthlatest** [comment]
@aario There is an issue in your docker-compose stack file. The `elasticsearch` image you are using doesn't accept the elasticsearch.yml configs as environment variables. You can also see this by checking the cluster name, it doesn't get set.

They would rather need to be passed as a command.

`Note:` This is specific to how an image is built. For instance, the official image from elastic.co takes these configs as environment variables.

Here's a compose file that works:

```
version: '3'
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    command: elasticsearch -Ecluster.name=catalog -Ebootstrap.memory_lock=true -Ehttp.port=9200 -Ehttp.cors.allow-origin="http://127.0.0.1:1358" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true -Ediscovery.zen.unicast.hosts=elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
     - "9200:9200"
  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    ports:
     - "1358:1358"
    links:
      - elasticsearch
```
