### ISSUE TITLE
Trouble accessing locally with docker

### ISSUE THREAD

**Issue by caseydm** [appbaseio/dejaVu#237]
I am trying to use dejavu through a local docker image. When I try to view my cluster in Chrome (version 69.0.3497.100) using http://localhost:1358/, and the settings http://localhost:9200 and my index name, I get the error:

`Failed to load http://localhost:9200/_aliases: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1358' is therefore not allowed access.`

This is the relevant portion of my docker-compose file:

```
version: '3'
services:
  # search engine
  elasticsearch:
    image: elasticsearch:5.6.10
    container_name: elasticsearch
    environment:
      - http.port=9200
      - http.cors.allow-origin="http://localhost:1358"
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ports:
     - "9200:9200"
    volumes:
       - elasticsearch-data:/usr/share/elasticsearch/data
  # elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    ports:
     - "1358:1358"
    links:
      - elasticsearch
```
Any clue on what I'm doing wrong?

**Comment by forelabs** [comment]
I have some similar problem.
I am not able to connect to my elasticsearch within docker-compose with dejavu, but it works with e.g. elastichq:
![image](https://user-images.githubusercontent.com/3809644/50509271-8d5b2680-0a85-11e9-8bdd-d658a98c5d76.png)

so when you are wihtin the docker-compose setup, all of your containers run in the same network and can be accessed through their names as hostname. but this does not work for dejavu.

i use following setup:
```
  dejavu:
    ports:
      - "5005:1358"
    image: appbaseio/dejavu:3.0.0-alpha
    links:
      - elasticsearch

  elastichq:
    ports:
      - "5000:5000"
    image: elastichq/elasticsearch-hq

  elasticsearch:
    ports:
      - "19200:9200"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    logging:
      driver: "json-file"
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - http.cors.allow-origin="http://localhost:*"
      - http.cors.enabled=true
      - http.cors.allow-headers="X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx512m"
```

hope someone can help you/me/us
