### ISSUE TITLE
CORS issues when running using docker-compose

### ISSUE THREAD

**Issue by janheinrichmerker** [appbaseio/dejaVu#256]
When I run Elasticsearch and Dejavu using docker-compose, I get CORS errors even though I configured it in the docker-compose.yml.

#### docker-compose.yml
```yaml
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - http.port=9200
      - "http.cors.allow-origin=http://localhost:1358"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.2
    container_name: kibana
    environment:
      SERVER_NAME: kibana-server
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  cerebro:
    image: yannart/cerebro:0.8.1
    container_name: cerebro
    networks:
      - esnet
    ports:
      - "9900:9000"
    depends_on:
      - elasticsearch

  dejavu:
    image: appbaseio/dejavu:2.0.5
    container_name: dejavu
    ports:
      - "1358:1358"
    networks:
      - esnet
    links:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge
```
