### ISSUE TITLE
Query Explorer does not work with the local dockerized ElasticSearch instance

### ISSUE THREAD

**Issue by mephi42** [appbaseio/dejaVu#306]
I'm trying to use dejavu with `elasticsearch:6.4.2` docker image.
Here are my docker-compose definitions:

```
  dejavu:
    image: appbaseio/dejavu:3.2.3
    container_name: dejavu
    ports:
     - 1358:1358
  elasticsearch:
    image: elasticsearch:6.4.2
    environment:
      discovery.type: single-node
      http.port: 9200
      http.cors.enabled: 'true'
      http.cors.allow-origin: http://localhost:1358,http://127.0.0.1:1358
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: 'true'
    ports:
      - 9200:9200
```

Data Browser works, but Query Explorers tells me that "It looks like your app name, username, password combination doesn't match. Check your url and appname and then connect it again.". When working with Data Browser, network analysis developer tool shows requests to the dockerized ES instance, but when trying to use Query Explorer no requests are seen.

Edit 1: I have checked that the ElasticSearch daemon process was given the environment variables:

```
elastic+     1     0 39 09:41 ?        00:00:36 /opt/jdk-10.0.2/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.io.tmpdir=/tmp/elasticsearch.Nl6gW7bV -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Djava.locale.providers=COMPAT -XX:UseAVX=2 -Des.cgroups.hierarchy.override=/ -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/usr/share/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=tar -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -Ehttp.port=9200 -Ediscovery.type=single-node -Ehttp.cors.enabled=true -Ehttp.cors.allow-credentials=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358```
```

Edit 2: There are the following messages in the developer console:

```
Laden von gemischten aktiven Inhalten "http://localhost:9200/db/_settings?human" wurde blockiert.[Weitere Informationen] vendor.min.js:9:20214
Laden von gemischten aktiven Inhalten "http://localhost:9200/db/_mapping/" wurde blockiert.[Weitere Informationen] vendor.min.js:9:20214
```

(meaning: loading of mixed active content was blocked). I can see that somehow the same URLs are retrieved successfully by the Data Browser.

Edit 3: I've added `https://opensource.appbase.io` to `http.cors.allow-origin` list and Query Explorer started working in Chrome (but still not in Firefox). This doesn't look right, because I'm using a local dejavu instance.

**Comment by chrissound** [comment]
Same issue

**Comment by lakhansamani** [comment]
@mephi42 @chrissound  Firefox has a strict mixed content policy so it is very difficult to connect local app on a hosted instance.

With recent versions of chrome mixed content is allowed. Though we have a chrome extension for Query Explorer, which you can use for local instances.
We recommend using Chrome for this kind of operations.

**Comment by vakrolme** [comment]
Same error with the setup below. Should it be supported?

**Dejavu** 3.4.6
**Elasticsearch** 7.6.0
**Chrome** Version 81.0.4044.129 (Official Build) (64-bit)
_Insecure content_ explicitly allowed in Site Settings
```
#./docker-compose.yml

version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    container_name: elasticsearch
    restart: always
    volumes:
      - ./tmp/esdata1:/usr/share/elasticsearch/data:delegated
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358,https://opensource.appbase.io/
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m

  dejavu:
      image: appbaseio/dejavu:latest
      container_name: dejavu
      ports:
        - '1358:1358'
      links:
        - elasticsearch
```
<img width="807" alt="Screen Shot 2020-05-05 at 21 29 32" src="https://user-images.githubusercontent.com/17144873/81107779-fbd0b400-8f17-11ea-8832-41d1ceb85b83.png">
