### ISSUE TITLE
[Search Preview] No data found. Please insert data to use this feature

### ISSUE THREAD

**Issue by tamersalama** [appbaseio/dejaVu#319]
The Search Preview is giving the message of No data found.

I'm connecting to a local instance where I can load and view/edit data through the other functions. The same server connection and application (index) is showing the above message in Search Preview.

My elasticsearch instance is NOT dockerized and I'm using dockerized Dejavu.

No apparent errors in js console.

Any ideas?

**Comment by gkostin1966** [comment]
I was experiencing this in Docker. 
I was able to get it to work by allowing everything for CORS...

```
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - 'opensearch-data:/usr/share/opensearch/data'
    networks:
      - opensearch-net
```
