### ISSUE TITLE
Still do not know how to connect to Elasticsearch running on GCP

### ISSUE THREAD

**Issue by dkajtoch** [appbaseio/dejaVu#351]
I am running dejavu and elasticsearch on Google Cloud virtual machine from inside Docker container. I m using docker-compose.yaml (below). I opened firewall on ports 9200, 9300, 1358. I have static ip address attached to the machine. I can open dejavu by running `http://static_ip:1358` and I can even play with Elasticsearch on port 9200, by running e.g. `http://static_ip:9200` or `http::static_ip:9200/test_index`. I tried connecting to elasticsearch from dejavu front on multiple ways `http://localhost:9200`, `http://127.0.0.1`, `http://elasticsearch:9200`, `http://static_ip:9200`. Nothing works. Any advice?
```
version: '3'
services:
    # search engine
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.1
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - http.port=9200
            - http.cors.enabled=true
            - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
            - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
            - http.cors.allow-credentials=true
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
               soft: -1
               hard: -1
        volumes:
          -esdata01:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'
            - '9300:9300'
    # elasticsearch browser
    dejavu:
        image: appbaseio/dejavu:3.2.3
        container_name: dejavu
        ports:
            - '1358:1358'
        links:
            - elasticsearch
volumes:
   esdata01:
      driver: local
  
```
