### ISSUE TITLE
can't get it to work/connect

### ISSUE THREAD

**Issue by samthomson** [appbaseio/dejavu#40]
- elastic search is running and I can browse data using sense.
- installed dejavu as a chrome extension
- no instruction as to what I should enter for appname or host, tried appname as anything and host as 'localhost' and 'localhost:9200', all of which result in dejavu blocking any user input and continual blue loader at top
- tried host as 'http://localhost:9200' and 'http://127.0.0.1:9200' which also don't work, but at least get an 'authentication' error
- tried with above hosts and using my index name for app name, still the same authentication error.

Looks like a great tool, just what I've been looking for, but needs a getting started/how to use section in the read me.

**Comment by farhan687** [comment]
hi @samthomson 
Solution
- You should write existing index in appname input box.
- and if you already did the above step and still you have the issue, set the CORS setting in elasticsearch config file.

Note: Elasticsearch has a CORS header issue with v2.3.0, use v2.3.2 and above.

```yml
http.port: 9200
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
http.cors.allow-credentials: true
```

If you use dejavu as elasticsearch plugin, dejavu will fetch the existing indices for you and you just need to select one of the existing indices.
